class_path: minerva.data.data_modules.har_xu_23.HarDataModule
init_args:
  processed_data_dir: "/workspaces/HIAAC-KR-Dev-Container/shared_data/xu_2023_datasets/1-1/rw-tight/processed/"
  window_size: 60
  batch_size: 16
  adf: False
  use_train_as_val: False